version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - log:/usr/src/app/logs
  promtail:
    image: grafana/promtail:main
    ports:
      - "8090:8090"
    depends_on:
      - web
    command: -config.file=/etc/promtail/config.yaml
    volumes:
      - log:/var/custom_log
      - ./promtail/config.yaml:/etc/promtail/config.yaml
volumes:
  log: {}
