server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  # Reemplazar por las que le da el front de grafana
  url: https://logs-prod3.grafana.net/api/prom/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: logs
          __path__: /var/custom_log/logfile.log
